services:
  - type: web
    name: gesotec
    runtime: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
