-- Eliminar tabla si existe para asegurar estructura correcta
DROP TABLE IF EXISTS base_conocimiento CASCADE;

-- Crear tabla para la Base de Conocimiento
CREATE TABLE base_conocimiento (
    id BIGSERIAL PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    descripcion TEXT NOT NULL,
    categoria VARCHAR(100) NOT NULL,
    icono VARCHAR(50) NOT NULL,
    palabras_clave TEXT[] NOT NULL,
    solucion TEXT NOT NULL,
    creado_por BIGINT REFERENCES usuarios(id) ON DELETE SET NULL,
    fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    fecha_actualizacion TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Crear índice para búsquedas por palabras clave
CREATE INDEX idx_base_conocimiento_palabras_clave ON base_conocimiento USING GIN(palabras_clave);

-- Crear índice para búsquedas por categoría
CREATE INDEX idx_base_conocimiento_categoria ON base_conocimiento(categoria);

-- Crear índice para búsquedas por título
CREATE INDEX idx_base_conocimiento_titulo ON base_conocimiento(titulo);

-- Insertar problemas frecuentes iniciales
INSERT INTO base_conocimiento (titulo, descripcion, categoria, icono, palabras_clave, solucion, creado_por) VALUES
    ('No puedo conectarme al WiFi', 'Problemas de conexión a la red inalámbrica de la empresa', 'Red', '📶', ARRAY['wifi', 'red', 'internet', 'conexión', 'inalámbrica'], '1. Reinicia tu dispositivo\n2. Verifica que el WiFi esté activado\n3. Intenta olvidar la red y volver a conectarte\n4. Si persiste, contacta al departamento de TI', NULL),
    ('Impresora no responde', 'La impresora no imprime o no se detecta', 'Hardware', '🖨️', ARRAY['impresora', 'print', 'imprimir', 'papel', 'tinta'], '1. Verifica que la impresora esté encendida\n2. Revisa el nivel de papel y tinta\n3. Verifica que esté conectada al puerto USB o red\n4. Reinicia la impresora y tu computadora', NULL),
    ('Olvidé mi contraseña', 'No puedo acceder a mi cuenta por contraseña olvidada', 'Seguridad', '🔐', ARRAY['contraseña', 'password', 'acceso', 'login', 'sesión'], '1. Haz clic en ''¿Olvidaste tu contraseña?'' en la pantalla de login\n2. Ingresa tu correo electrónico\n3. Sigue las instrucciones del correo de recuperación\n4. Si no recibes el correo, contacta al soporte', NULL),
    ('Computadora lenta', 'El sistema funciona lentamente o se congela', 'Hardware', '💻', ARRAY['lento', 'lentitud', 'congelado', 'freeze', 'rendimiento'], '1. Cierra programas innecesarios\n2. Reinicia tu computadora\n3. Verifica el espacio en disco\n4. Ejecuta un análisis de antivirus\n5. Si el problema persiste, solicita mantenimiento', NULL),
    ('No puedo abrir un archivo', 'El archivo no se abre o muestra error', 'Software', '📄', ARRAY['archivo', 'documento', 'abrir', 'error', 'corrupto'], '1. Verifica que tengas el programa necesario para abrir el archivo\n2. Intenta abrir el archivo en otra aplicación\n3. Verifica que el archivo no esté corrupto\n4. Si es un archivo compartido, solicita que lo reenvíen', NULL),
    ('Correo electrónico no llega', 'No recibo o no puedo enviar correos', 'Software', '📧', ARRAY['correo', 'email', 'mail', 'enviar', 'recibir'], '1. Verifica tu conexión a internet\n2. Revisa la carpeta de spam\n3. Verifica que la dirección del destinatario sea correcta\n4. Limpia la caché del navegador de correo\n5. Contacta al administrador si el problema persiste', NULL),
    ('Pantalla azul de muerte', 'La computadora muestra pantalla azul y se reinicia', 'Hardware', '🔵', ARRAY['pantalla azul', 'blue screen', 'bsod', 'crash', 'reinicia'], '1. Reinicia la computadora\n2. Anota el código de error que aparece\n3. Desconecta dispositivos externos\n4. Si el problema persiste, crea un ticket de soporte técnico', NULL),
    ('VPN no conecta', 'No puedo conectarme a la VPN de la empresa', 'Red', '🔒', ARRAY['vpn', 'red privada', 'remoto', 'trabajo desde casa'], '1. Verifica tu conexión a internet\n2. Reinicia el cliente VPN\n3. Verifica tus credenciales de VPN\n4. Desactiva temporalmente el firewall\n5. Contacta al departamento de TI si el problema persiste', NULL),
    ('Mouse o teclado no funciona', 'El mouse o teclado no responde', 'Hardware', '⌨️', ARRAY['mouse', 'teclado', 'ratón', 'periférico', 'input'], '1. Verifica que estén conectados correctamente\n2. Si son inalámbricos, cambia las baterías\n3. Prueba en otro puerto USB\n4. Reinicia la computadora\n5. Si el problema persiste, solicita un reemplazo', NULL),
    ('No puedo acceder a un sistema', 'Error al intentar ingresar a un sistema específico', 'Software', '🚫', ARRAY['sistema', 'acceso', 'denegado', 'error', 'permisos'], '1. Verifica que tus credenciales sean correctas\n2. Limpia la caché del navegador\n3. Intenta en otro navegador\n4. Verifica que tengas los permisos necesarios\n5. Contacta al administrador del sistema', NULL),
    ('No puedo acceder a OneDrive', 'Error al sincronizar o acceder archivos en OneDrive', 'Software', '☁️', ARRAY['onedrive', 'nube', 'sincronizar', 'archivos', 'cloud'], '1. Verifica tu conexión a internet\n2. Reinicia la aplicación de OneDrive\n3. Cierra sesión y vuelve a entrar\n4. Verifica que tengas espacio disponible\n5. Si el problema persiste, contacta al soporte', NULL),
    ('No puedo acceder a carpeta compartida', 'No tengo permisos para acceder a carpeta en red', 'Red', '📁', ARRAY['carpeta', 'compartida', 'red', 'acceso', 'permisos'], '1. Verifica que estés conectado a la red de la empresa\n2. Reinicia tu computadora\n3. Intenta acceder usando la dirección IP de la carpeta\n4. Solicita permisos al propietario de la carpeta\n5. Contacta al departamento de TI si el problema persiste', NULL),
    ('El sonido no funciona', 'No hay sonido en la computadora', 'Hardware', '🔊', ARRAY['sonido', 'audio', 'volumen', 'altavoces', 'speakers'], '1. Verifica que el volumen no esté en mute\n2. Revisa que los altavoces estén conectados\n3. Reinicia tu computadora\n4. Verifica los controladores de audio\n5. Si el problema persiste, solicita soporte técnico', NULL),
    ('La pantalla está muy oscura', 'No se ve bien la pantalla del monitor', 'Hardware', '🖥️', ARRAY['pantalla', 'monitor', 'brillo', 'oscura', 'oscuro'], '1. Ajusta el brillo del monitor usando los botones físicos\n2. Presiona las teclas de brillo en tu teclado\n3. Verifica que el cable del monitor esté bien conectado\n4. Reinicia tu computadora\n5. Si el problema persiste, solicita soporte técnico', NULL),
    ('No puedo imprimir en color', 'La impresora solo imprime en blanco y negro', 'Hardware', '🎨', ARRAY['color', 'impresora', 'imprimir', 'blanco y negro', 'bn'], '1. Verifica que la impresora tenga tinta de color\n2. En el documento, selecciona "Color" en las opciones de impresión\n3. Verifica que no esté seleccionada la opción "Escala de grises"\n4. Reinicia la impresora\n5. Si el problema persiste, contacta al soporte', NULL),
    ('El navegador está muy lento', 'Las páginas web cargan muy lentamente', 'Software', '🌐', ARRAY['navegador', 'internet', 'lento', 'cargar', 'web'], '1. Cierra pestañas que no uses\n2. Limpia el historial y caché del navegador\n3. Desactiva extensiones que no necesites\n4. Reinicia el navegador\n5. Si el problema persiste, intenta con otro navegador', NULL),
    ('No puedo descargar archivos', 'Los archivos no se descargan o se cortan', 'Software', '⬇️', ARRAY['descargar', 'descarga', 'archivo', 'download', 'bajar'], '1. Verifica tu conexión a internet\n2. Limpia la caché del navegador\n3. Desactiva el antivirus temporalmente\n4. Intenta descargar en otra carpeta\n5. Si el problema persiste, contacta al soporte', NULL),
    ('El teclado escribe letras incorrectas', 'Al presionar teclas aparecen otras letras', 'Hardware', '⌨️', ARRAY['teclado', 'letras', 'incorrectas', 'error', 'escribir'], '1. Verifica que el idioma del teclado sea el correcto\n2. Presiona Alt + Shift para cambiar el idioma\n3. Reinicia tu computadora\n4. Si es teclado inalámbrico, cambia las baterías\n5. Si el problema persiste, solicita un reemplazo', NULL),
    ('No puedo conectar auriculares Bluetooth', 'Los auriculares Bluetooth no se conectan', 'Hardware', '🎧', ARRAY['auriculares', 'bluetooth', 'audio', 'conectar', 'inalámbricos'], '1. Activa el Bluetooth en tu dispositivo\n2. Pon los auriculares en modo de emparejamiento\n3. Selecciona los auriculares en la lista de dispositivos\n4. Si no aparecen, reinicia el Bluetooth\n5. Si el problema persiste, verifica que los auriculares tengan batería', NULL),
    ('La batería de la laptop se descarga rápido', 'La batería dura muy poco tiempo', 'Hardware', '🔋', ARRAY['batería', 'laptop', 'portátil', 'descarga', 'carga'], '1. Reduce el brillo de la pantalla\n2. Cierra programas que consuman mucha energía\n3. Desactiva WiFi y Bluetooth si no los usas\n4. Verifica que la batería esté bien calibrada\n5. Si el problema persiste, solicita reemplazo de batería', NULL),
    ('No puedo encontrar un archivo', 'Busqué un archivo pero no lo encuentro', 'Software', '🔍', ARRAY['archivo', 'buscar', 'encontrar', 'perdido', 'buscador'], '1. Usa la función de búsqueda en tu computadora\n2. Verifica en la carpeta de Descargas\n3. Busca en la Papelera de reciclaje\n4. Si lo borraste por error, restaura desde la Papelera\n5. Si no lo encuentras, verifica si lo guardaste en otra carpeta', NULL),
    ('El programa se cierra solo', 'Una aplicación se cierra inesperadamente', 'Software', '❌', ARRAY['programa', 'cierra', 'crash', 'error', 'aplicación'], '1. Reinicia el programa\n2. Reinicia tu computadora\n3. Actualiza el programa a la última versión\n4. Verifica que tu computadora cumpla los requisitos\n5. Si el problema persiste, reinstala el programa', NULL),
    ('No puedo pegar texto', 'La función de copiar y pegar no funciona', 'Software', '📋', ARRAY['pegar', 'copiar', 'texto', 'clipboard', 'portapapeles'], '1. Reinicia tu computadora\n2. Intenta usar Ctrl+V para pegar\n3. Cierra otros programas que puedan interferir\n4. Reinicia la aplicación donde intentas pegar\n5. Si el problema persiste, reinicia tu computadora', NULL),
    ('El mouse se mueve solo', 'El cursor del mouse se mueve sin que yo lo toque', 'Hardware', '🖱️', ARRAY['mouse', 'cursor', 'solo', 'mueve', 'automático'], '1. Limpia el sensor del mouse\n2. Si es inalámbrico, verifica que no haya interferencias\n3. Desconecta y vuelve a conectar el mouse\n4. Si es mouse de laptop, desactiva el touchpad temporalmente\n5. Si el problema persiste, solicita un reemplazo', NULL),
    ('No puedo cambiar el fondo de pantalla', 'No me deja personalizar el escritorio', 'Software', '🖼️', ARRAY['fondo', 'pantalla', 'escritorio', 'personalizar', 'wallpaper'], '1. Haz clic derecho en el escritorio\n2. Selecciona "Personalizar"\n3. Elige "Fondo de escritorio"\n4. Selecciona la imagen que deseas\n5. Si no funciona, reinicia tu computadora', NULL),
    ('El reloj muestra la hora incorrecta', 'La hora del sistema no es correcta', 'Software', '🕐', ARRAY['hora', 'reloj', 'fecha', 'tiempo', 'incorrecta'], '1. Haz clic derecho en el reloj\n2. Selecciona "Ajustar fecha/hora"\n3. Activa "Ajustar automáticamente"\n4. Si no funciona, establece la hora manualmente\n5. Reinicia tu computadora', NULL),
    ('No puedo abrir PDF', 'Los archivos PDF no se abren', 'Software', '📕', ARRAY['pdf', 'archivo', 'documento', 'leer', 'abrir'], '1. Verifica que tengas un lector de PDF instalado\n2. Descarga Adobe Acrobat Reader si no lo tienes\n3. Intenta abrir el archivo con otro programa\n4. Verifica que el archivo no esté corrupto\n5. Si el problema persiste, solicita que te reenvíen el archivo', NULL),
    ('La computadora hace mucho ruido', 'El ventilador o la computadora hacen ruido extraño', 'Hardware', '🔊', ARRAY['ruido', 'ventilador', 'sonido', 'ruidoso', 'fan'], '1. Limpia los ventiladores de polvo\n2. Verifica que no haya obstrucciones\n3. Cierra programas que consuman muchos recursos\n4. Si el ruido es muy fuerte, apaga la computadora\n5. Contacta al soporte técnico para revisión', NULL),
    ('No puedo conectarme a videollamada', 'Error al entrar a reuniones por video', 'Software', '📹', ARRAY['videollamada', 'zoom', 'meet', 'teams', 'reunión'], '1. Verifica tu conexión a internet\n2. Cierra otros programas que usen cámara/micrófono\n3. Actualiza la aplicación de videollamada\n4. Verifica que la cámara y micrófono funcionen\n5. Si el problema persiste, intenta con otra aplicación', NULL),
    ('El WiFi se desconecta solo', 'La conexión a internet se corta intermitentemente', 'Red', '📶', ARRAY['wifi', 'desconecta', 'corta', 'intermitente', 'internet'], '1. Reinicia tu router o módem de internet\n2. Olvida la red y vuelve a conectarte\n3. Actualiza los controladores de WiFi\n4. Verifica que no haya interferencias de otros dispositivos\n5. Contacta al departamento de TI si el problema persiste', NULL),
    ('No puedo instalar un programa', 'Error al instalar software', 'Software', '💿', ARRAY['instalar', 'programa', 'software', 'error', 'aplicacja'], '1. Verifica que tengas permisos de administrador\n2. Desactiva el antivirus temporalmente\n3. Verifica que haya suficiente espacio en disco\n4. Descarga el programa nuevamente\n5. Si el problema persiste, contacta al soporte técnico', NULL),
    ('La pantalla se congela', 'La pantalla se queda congelada y no responde', 'Hardware', '❄️', ARRAY['congelada', 'pantalla', 'freeze', 'no responde', 'bloqueada'], '1. Presiona Ctrl + Alt + Supr para abrir el administrador de tareas\n2. Cierra el programa que no responde\n3. Si no funciona, reinicia tu computadora\n4. Desconecta dispositivos externos\n5. Si el problema persiste, crea un ticket de soporte', NULL);
